spring:
  jpa:
    open-in-view: false
    show-sql: true
  properties:
    hibernate.format_sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    open-in-view: false

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema/schema.sql