name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Build With Gradle
        run: ./gradlew clean build
        
      - name: Make Directory
        run: mkdir -p deploy
        
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp ./scripts/deploy.sh ./deploy
        
      - name: Make zip file
        run: zip -r ./deploy.zip ./deploy
        shell: bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Upload to S3
        run: aws s3 cp ./deploy.zip s3://$S3_BUCKET_NAME/ --region ap-northeast-2

      - name: Deploy
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        run: aws deploy create-deployment --application-name deploy --deployment-group-name deploy-group --file-exists-behavior OVERWRITE --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=deploy.zip --region ap-northeast-2
